### ISSUE TITLE
Options for acts_as_group like class name for group_membership

### ISSUE THREAD

**Issue by byronduenas** [dwbutler/groupify#19]
It would be nice if you could specify the the class name for group_membership, to have the ability for two types of groups to exist in a project, and users can belong to both these types of groups

**Comment by byronduenas** [comment]
Another problem I've had with this issue is that Group is hardcoded to look for a 'GroupMembership' model, and the group membership class cannot be named something else or name spaced

**Comment by dwbutler** [comment]
I'm open to suggestions. Maybe the names of these classes could be specified via configuration?

**Comment by kcollignon** [comment]
+1

**Comment by abner** [comment]
+1. The group membership class passed as an attribute would be a nice plus.

**Comment by dwbutler** [comment]
It's simple enough to make the class name of the group membership model configurable. However, all Groupify groups and group members must use the same model. It's the only way to support the different kinds of membership queries, which join different models to the same group memberships table.
