### ISSUE TITLE
users won't stick in groups

### ISSUE THREAD

**Issue by Yorkshireman** [dwbutler/groupify#26]
I set it up as per the documentation (I think).

But then in the console:

user=User.new group=Group.new group.add user user.in_group?(group)

=> false

Returns false, instead of true.

Problem.

I don't get it. I've a few different things and no joy. I'm stuck.

My latest attempt is here: https://github.com/Yorkshireman/sebcoles/tree/setup3 (setup3 branch)

I have a previous attempt on setup2.

There is little difference between the two branches (the migrations and subsequent scheme.rb were SLIGHTLY different).

Help!

**Comment by dwbutler** [comment]
Based on the sample code you provided, I'm not sure that you're actually saving anything into the database. You have to call `User.create` or `user.save` at some point to get your models persisted into the database.

It would be helpful if you could provide a full example, perhaps in a gist or in unit tests in your project.
