### ISSUE TITLE
Error on add user a team on Rails 5 Beta

### ISSUE THREAD

**Issue by mninaut** [dwbutler/groupify#39]
`private method `clear_association_cache' called for #<User:0x007fc2638bf150> Did you mean? clear_transaction_record_state
`

clear_association_cache is private in Rails5. …	but I don`t  fix it =/

**Comment by dwbutler** [comment]
Hi,

Thanks for the bug report. Groupify doesn't support Rails 5 yet, so I'm sure there will be lots of things broken until I've found some time to go through the upgrade process.

**Comment by wadestuart** [comment]
Added a PR #44 to prep it for rails 5,   basically using .send() which is what most other projects that use clear_association_cache are doing.   The PR also allows < 5.1 on in the gemspec and fixes a depreciation error in the specs.

**Comment by dwbutler** [comment]
Awesome, thanks!

**Comment by wadestuart** [comment]
no problem,  thanks for the gem!

**Comment by dwbutler** [comment]
Released 0.5.2 with Rails 5 support. This was a teeny version bump because this was more like a backwards compatible bug fix than a new feature.
