### ISSUE TITLE
Sample Application Broken

### ISSUE THREAD

**Issue by igostavro** [dwbutler/groupify#43]
I tried integrating your sample application, but when i try to create a new group i get a crash here:

```
NoMethodError at /groups/new
undefined method `name' for #<Group id: nil, type: nil>

   </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
```

Any ideas?

**Comment by dwbutler** [comment]
The default Groupify migration doesn't add a name column to the groups table. You'd have to modify it and add it yourself. See #41
