### ISSUE TITLE
Removing Users From a Group  [QUESTION]

### ISSUE THREAD

**Issue by dccakes** [dwbutler/groupify#59]
I have been playing around with groupify before using in a project of  mine and I am having issue removing users from a given group whenever I do the following line:

    group.users.delete(user, as: 'manager')  

I am able to correctly create the group, then add a user with the correct membership type. However, when I try and delete a user using the line above, I get the following error:

    NoMethodError: undefined method `users' for #<Group id: 1, type: nil>

This also occurs anytime I try and use "group.users".  I am able to croeectly delete a user using:

    user.groups.destroy(group, as: 'manager') 

Any help would be appreciated. 

My models are as follows:

    class GroupMembership < ActiveRecord::Base
      groupify :group_membership
    end

    class Group < ActiveRecord::Base
      groupify :group
    end

    class User < ApplicationRecord
      groupify :group_member
      groupify :named_group_member
      
      devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable, :invitable
    end

**Comment by dwbutler** [comment]
Did you still need help with this? Not sure if you closed the issue by accident.

**Comment by dwbutler** [comment]
You have to specify which members belong to the group, so that Groupify can create the associations.

```ruby
class Group < ActiveRecord::Base
  groupify :group, members: [:users]
end
```
