### ISSUE TITLE
`in_only_groups` doesn't match on group IDs

### ISSUE THREAD

**Issue by joelvh** [dwbutler/groupify#62]
It appears that `in_only_groups` finds members that are members of exactly the same number of groups passed to the method. However, it does not make sure to match on the exact same groups.

For instance, if a user is in group1, group2, and group3, and I find `User.in_only_groups(group2, group3, group4)`, it will return my user, even though they are not in the exact same 3 groups.

Am I misunderstanding this method?

https://github.com/dwbutler/groupify/blob/master/lib/groupify/adapter/active_record/group_member.rb#L133

**Comment by joelvh** [comment]
What it should do is match the number of groups (as it does), but also `LEFT OUTER JOIN` on the `group_memberships` table again and filter on the group IDs to see if the total number of groups they're a member of equals the specific groups given.

Is there another way to solve that without the additional join?

**Comment by joelvh** [comment]
One more thought. This gets complicated with calling `User.in_only_groups(group1, group2).as('role')` because the role needs to be factored in on both joins when `as` is called.

**Comment by dwbutler** [comment]
Yes, you're right. I noticed this problem before and fixed it in https://github.com/dwbutler/groupify/pull/58. It's been a busy few weeks and I haven't had a chance to release it.

IIRC my fix doesn't work with role filtering.

**Comment by joelvh** [comment]
@dwbutler OK, great. I'll close this issue.
