### ISSUE TITLE
Relationship between two models

### ISSUE THREAD

**Issue by Wooody82** [dwbutler/groupify#69]
Hi,
Is it possible to create join between two models, I am not sure if its right but the idea is more like this:
User1 with Manager role will add a POST1
User2 with Coworker role can send a request to join POST1 to be a Team member of POST1.
User1 can send request to let user2 be part of Teams
User1/User2 can approve or reject if they got request.
If anyone removes the relation so it's removed from both.

Any idea or way to do that.

**Comment by monroemann** [comment]
@malasaad82 From reading the documentation, I think that is possible.  You'd have to do the coding with some <if> statements, i.e. if Manager clicks 'accept', then Coworker can join Post1.  You could do this with protected pages, or even within the post itself, i.e. you code it so the 'post' button will not work unless Manager has 'accepted' coworker.

**Comment by dwbutler** [comment]
Groupify can model who belongs to what group, and what role they play in that group. A membership request could potentially be modeled by adding the user to the group with membership type of "requested." If you want to track more lifecycle attributes of the membership request, like when it was created and whether it was accepted or rejected and by who, you are better off storing that information in a separate `membership_requests` table.
