### ISSUE TITLE
Rails 5.1.5 Support

### ISSUE THREAD

**Issue by rposborne** [dwbutler/groupify#70]
Rails 5.1.5 appears to be causing failures throughout this gem's test suite
```
ActiveRecord::HasManyThroughOrderError:
       Cannot have a has_many :through association 'User#groups' which goes through 'User#group_memberships_as_member' before the through association is defined.
```

This appears to be caused by this recent commit in rails. 

https://github.com/rails/rails/commit/652258e41a882acccdb9a3ce211dbf356e738b28

This may be a bug in rails, but wanted to flag this here for others.

**Comment by mcrundo** [comment]
changing the order, as shown in the docs, on the user model seems to have worked for me:

`groupify :named_group_member`

`groupify :group_member`

**Comment by rposborne** [comment]
Yup that seems to do it
